### ISSUE TITLE
Type error when using value given to auto-set context

### ISSUE THREAD

**Issue by saturnonearth** [Hugos68/svelte-contextify#19] opened 2024-01-19 03:23 UTC
I have this code:

```ts
const dialogs = {
   section: writable(false),
   heading: writable(false),
};

export const [getDialogStates, setDialogStates, key] = createContext<typeof dialogs>(dialogs);
```

When I run 

```ts
setDialogStates();
```

in my `+layout.svelte` I get a type error saying, `Expected 1 arguments, but got 0` - even though, it seems to work.

**Comment by Hugos68** [comment] 2024-01-21 16:58
Hey @saturnonearth the setter function requires you to specify a value since you are setting the context, if you are only interested in retrieving the value the `getDialogStates` function is a better fit, since I don't see any bugs or unintended behavior I am going to close this issue.

**Closed as completed by Hugos68** 2024-01-21 16:58 UTC
